In [1]:
import numpy as np 
a = np.array([1, 2, 3])
print(a)
element = a[1]
print(element)

[1 2 3]
2


In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Matrix:')
print(matrix)

element = matrix[0, 0]
print(element)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1


In [17]:
a = np.zeros(4)
print(a)

a = np.ones(4)
print(a)

a = np.empty(4)
print(a)

a = np.arange(10)
print(a)

a = np.linspace(0, 10, num=6)
print(a)

a = np.ones(5, dtype = np.int64)
a

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]
[ 0.  2.  4.  6.  8. 10.]


array([1, 1, 1, 1, 1], dtype=int64)